CREATE TABLE category (
	id SERIAL PRIMARY KEY,
	name VARCHAR (32) NOT NULL,
	description VARCHAR (128) NOT NULL
);

CREATE TABLE product (
	id SERIAL PRIMARY KEY,
	category_id INT REFERENCES category (id) ON DELETE SET NULL,
	name VARCHAR (32) NOT NULL,
	description VARCHAR (128) NOT NULL,
	price DOUBLE PRECISION NOT NULL,
	status BOOLEAN NOT NULL,
	image_name VARCHAR (256) NOT NULL,
	creation_date TIMESTAMP NOT NULL
);

CREATE TABLE app_user (
	id SERIAL PRIMARY KEY,
	username VARCHAR (32) UNIQUE NOT NULL,
	password VARCHAR (256) NOT NULL,
	role VARCHAR (8) NOT NULL
);
